# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManualUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1199, 856)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.p10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p10.sizePolicy().hasHeightForWidth())
        self.p10.setSizePolicy(sizePolicy)
        self.p10.setAlignment(QtCore.Qt.AlignCenter)
        self.p10.setObjectName("p10")
        self.gridLayout.addWidget(self.p10, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.total_images = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.total_images.setFont(font)
        self.total_images.setObjectName("total_images")
        self.horizontalLayout_2.addWidget(self.total_images)
        self.lcurrent_image_no = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lcurrent_image_no.setFont(font)
        self.lcurrent_image_no.setObjectName("lcurrent_image_no")
        self.horizontalLayout_2.addWidget(self.lcurrent_image_no)
        self.total_targets = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.total_targets.setFont(font)
        self.total_targets.setObjectName("total_targets")
        self.horizontalLayout_2.addWidget(self.total_targets)
        self.x1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.x1.setFont(font)
        self.x1.setObjectName("x1")
        self.horizontalLayout_2.addWidget(self.x1)
        self.p1 = QtWidgets.QPushButton(self.centralwidget)
        self.p1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.p1.setObjectName("p1")
        self.horizontalLayout_2.addWidget(self.p1)
        self.crop = QtWidgets.QPushButton(self.centralwidget)
        self.crop.setObjectName("crop")
        self.horizontalLayout_2.addWidget(self.crop)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.previous = QtWidgets.QPushButton(self.centralwidget)
        self.previous.setObjectName("previous")
        self.horizontalLayout.addWidget(self.previous)
        self.next = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next.sizePolicy().hasHeightForWidth())
        self.next.setSizePolicy(sizePolicy)
        self.next.setObjectName("next")
        self.horizontalLayout.addWidget(self.next)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1199, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Edhitha Manual UI"))
        self.p10.setText(_translate("MainWindow", "TextLabel"))
        self.total_images.setText(_translate("MainWindow", "Total images : "))
        self.lcurrent_image_no.setText(_translate("MainWindow", "Current Image No:"))
        self.total_targets.setText(_translate("MainWindow", "Total Targets saved : "))
        self.x1.setText(_translate("MainWindow", "later"))
        self.p1.setText(_translate("MainWindow", "later button"))
        self.crop.setText(_translate("MainWindow", "Found Target!!"))
        self.previous.setText(_translate("MainWindow", "Previous"))
        self.next.setText(_translate("MainWindow", "Next"))



